## DATA CLEANING PROJECT##
use layoff;
SELECT * FROM LAYOFFS;
##1.REMOVE  DUPLIVCATE
##2.STANDARDIZE DATA
##REMOVILE NULLS ND BLANK
##REMOVE ANY COLUMNS

CREATE TABLE LAYOFFS_STAGING1
LIKE LAYOFFS;
SELECT* FROM LAYOFFS_STAGING1;
INSERT LAYOFFS_STAGING1
SELECT* 
FROM LAYOFFS;
SELECT* FROM LAYOFFS_STAGING1;
##REMOVING THE DUPLICATE##
SELECT* FROM LAYOFFS;
SELECT *,
ROW_NUMBER() OVER (PARTITION BY COMPANY,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS
ROW_NUM FROM LAYOFFS_STAGING1;
WITH DUPLICATE_CTE AS
(
SELECT *,
ROW_NUMBER() OVER (PARTITION BY COMPANY,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS
ROW_NUM FROM LAYOFFS_STAGING1)
SELECT* FROM 
DUPLICATE_CTE
WHERE ROW_NUM>1;
SELECT* FROM LAYOFFS_STAGING1
WHERE COMPANY='CASPER';
##U CANT DELETE OR UPDATE DUPLICATE CTE IN MYSQL;
WITH DUPLICATE_CTE AS
(
SELECT *,
ROW_NUMBER() OVER (PARTITION BY COMPANY,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS
ROW_NUM FROM LAYOFFS_STAGING1)
DELETE FROM 
DUPLICATE_CTE
WHERE ROW_NUM>1;







CREATE TABLE `layoffs_staging` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  `ROW_NUM` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SELECT* FROM LAYOFFS_STAGING;
INSERT LAYOFFS_STAGING
SELECT * FROM LAYOFFS_STAGING1;

INSERT INTO LAYOFFS_STAGING
SELECT *,
ROW_NUMBER() OVER (PARTITION BY COMPANY,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS
ROW_NUM FROM LAYOFFS_STAGING1;
SELECT * FROM LAYOFFS_STAGING;
SELECT* FROM LAYOFFS_STAGING
WHERE ROW_NUM>1;
DELETE FROM 
LAYOFFS_STAGING
WHERE ROW_NUM=2;
SET SQL_SAFE_UPDATES=0;
SELECT* FROM LAYOFFS_STAGING
WHERE ROW_NUM=2;

##STANDARDIZING DATA 
SELECT DISTINCT(TRIM(COMPANY))##TRIM TAKE OFF WHITE SAPCES
FROM LAYOFFS_STAGING;
UPDATE LAYOFFS_STAGING
SET COMPANY=TRIM(COMPANY);
SELECT DISTINCT INDUSTRY
FROM LAYOFFS_STAGING
ORDER BY 1;
SELECT *
FROM LAYOFFS_STAGING 
WHERE INDUSTRY LIKE 'CRYPTO%';
UPDATE LAYOFFS_STAGING
SET INDUSTRY ='CRYPTO'
WHERE INDUSTRY LIKE 'CRYPTO%';
SELECT DISTINCT INDUSTRY 
FROM LAYOFFS_STAGING;
SELECT DISTINCT LOCATION 
FROM LAYOFFS_STAGING
ORDER BY 1;
SELECT DISTINCT COUNTRY 
FROM LAYOFFS_STAGING
ORDER BY 1;
SELECT * 
FROM LAYOFFS_STAGING
WHERE COUNTRY LIKE 'UNITED STATES%';
SELECT DISTINCT COUNTRY,TRIM(TRAILING'.' FROM COUNTRY)
FROM LAYOFFS_STAGING
WHERE COUNTRY LIKE 'UNITED STATES%';
UPDATE LAYOFFS_STAGING 
SET COUNTRY= TRIM(TRAILING '.' FROM COUNTRY)
WHERE COUNTRY LIKE 'UNITED SATTES%';
SELECT COUNTRY 
FROM LAYOFFS_STAGING 
WHERE COUNTRY LIKE 'UNITED STATES%';
SELECT `DATE`,
STR_TO_DATE(`DATE`,'%m/%d/%y')
AS FORMATTED
FROm layoffs_staging;
UPDATE LAYOFFS_STAGING 
SET `date`=STR_TO_DATE(`DATE`,'%m/%d/%Y');
select `DATE`
FROM LAYOFFS_STAGING;
ALTER TABLE LAYOFFS_STAGING
MODIFY COLUMN `date` DATE;
select* from layoffs_staging;
SELECT* FROM LAYOFFS_STAGING
WHERE TOTAL_LAID_OFF IS NULL
AND PERCENTAGE_LAID_OFF is NULL;

UPDATE LAYOFFS_STAGING 
SELECT* FROM 
LAYOFFS_STAGING 
WHERE INDUSTRY IS NULL
OR INDUSTRY='';
SELECT * FROM LAYOFFS_STAGING
WHERE COMPANY='AIRBNB';
SELECT * 
FROM 
LAYOFFS_STAGING T1
JOIN LAYOFFs_STAGING T2
ON T1.COMPANY=T2.COMPANY
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY ='')
AND T2.INDUSTRY IS NOT NULL;
SELECT t1.INDUSTRY,T2.INDUSTRY
FROM 
LAYOFFS_STAGING T1
JOIN LAYOFFs_STAGING T2
ON T1.COMPANY=T2.COMPANY
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY ='')
AND T2.INDUSTRY IS NOT NULL;
UPDATE LAYOFFS_STAGINGT1
JOIN LAYOFFS_STAGING T2
ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY=T2.INDUSTRY
WHERE (T1.INDUSTRY IS NULL OR T1.INDUST='')
AND T2.INDUSTRY IS NOT NULL;
UPDATE LAYOFFS_STAGING
SET INDUSTRY =null
WHERE INDUSTRY='';

UPDATE LAYOFFS_STAGING T1
JOIN LAYOFFS_STAGING T2
ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY=T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL 
AND T2.INDUSTRY IS NOT NULL;
SELECT * FROM LAYOFFS_STAGING
WHERE COMPANY='AIRBNB';