CREATE DATABASE time_test;
USE time_test;
CREATE TABLE T_T( 
now_time TIME,
now_date DATE,
now_dt DATETIME
);
SELECT * FROM T_T;
INSERT INTO T_T
VALUES(CURRENT_TIME(),
CURRENT_DATE(),
NOW());
SELECT* FROM T_T;
INSERT INTO T_T
VALUES(CURRENT_TIME(),CURRENT_DATE()+1,NULL);
SELECT * FROM T_T;
